// backend/controllers/exifController.js

const exifr = require('exifr');

/**
 * extractEXIF(imageBuffer)
 * Uses exifr to extract metadata from an image buffer.
 * Returns key EXIF fields or a fallback message if none exist.
 */
async function extractEXIF(imageBuffer) {
  try {
    const metadata = await exifr.parse(imageBuffer);

    if (!metadata) {
      return {
        message:
          'No metadata found — this image may have been generated by AI or shared via social media which strips metadata'
      };
    }

    return {
      cameraMake: metadata.Make || null,
      cameraModel: metadata.Model || null,
      dateTaken: metadata.DateTimeOriginal || null,
      gps: metadata.gps || null,
      software: metadata.Software || null
    };
  } catch (err) {
    console.error('EXIF extraction error:', err);
    return {
      message:
        'No metadata found — this image may have been generated by AI or shared via social media which strips metadata'
    };
  }
}

module.exports = { extractEXIF };
